# Generated by Django 5.1.3 on 2024-11-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(max_length=250, verbose_name='Фильтры по видам спорта')),
                ('discipline', models.CharField(max_length=250, verbose_name='Фильтры по дисциплинам')),
                ('program', models.CharField(max_length=250, verbose_name='Фильтры по спортивной программе')),
                ('place', models.CharField(max_length=250, verbose_name='Фильтры месту проведения')),
                ('contestants_min', models.IntegerField(verbose_name='Фильтры по количеству участников мин')),
                ('contestants_max', models.IntegerField(verbose_name='Фильтры по количеству участников макс')),
                ('gender', models.CharField(max_length=250, verbose_name='Пол')),
                ('age', models.CharField(max_length=250, verbose_name='Фильтры по возрастной группе')),
                ('start_date', models.DateField(verbose_name='Фильтр по началу соревнования')),
                ('end_date', models.DateField(verbose_name='Фльтр по окончанию соревнования')),
                ('contest_type', models.CharField(max_length=250, verbose_name='Фильтры по уровню соревнования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
