# Generated by Django 5.1.3 on 2024-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilters',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='contest_type',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='contestants_max',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='contestants_min',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='place',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='program',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='sport_type',
        ),
        migrations.RemoveField(
            model_name='userfilters',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userfilters',
            name='filter_str',
            field=models.CharField(default='', max_length=500, verbose_name='Фильтры по видам спорта'),
            preserve_default=False,
        ),
    ]
