# Generated by Django 5.1.3 on 2024-11-23 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_rename_disctrict_region_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(verbose_name='Нижний порог')),
                ('end', models.IntegerField(verbose_name='Верхний порог')),
            ],
        ),
        migrations.CreateModel(
            name='ContestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Уровень соревнования')),
            ],
        ),
        migrations.CreateModel(
            name='GenderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.agegroup', verbose_name='Возрастная категория')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.gendergroup', verbose_name='Гендерная категория')),
            ],
        ),
        migrations.CreateModel(
            name='ContestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.category', verbose_name='Категория')),
                ('contest_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contesttype', verbose_name='Cоревнование')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=250, verbose_name='Программа')),
                ('code', models.CharField(max_length=250, verbose_name='Rод')),
                ('start', models.DateField(verbose_name='Дата начала')),
                ('end', models.DateField(verbose_name='Дата окончания')),
                ('contestants', models.IntegerField(verbose_name='Верхний порог')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country', verbose_name='Страна проведения')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.city', verbose_name='Город проведения')),
                ('contest_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contesttype', verbose_name='Уровень соревнования')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Вид спорта')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.sporttype', verbose_name='Вид спорта')),
            ],
        ),
    ]
