# Generated by Django 5.1.3 on 2024-11-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestcategory',
            old_name='contest_type',
            new_name='contest',
        ),
    ]
