# Generated by Django 5.1.3 on 2024-11-23 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_rename_contest_type_contestcategory_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contestants',
            field=models.IntegerField(verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='contestcategory',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest', verbose_name='Cоревнование'),
        ),
    ]
