# Generated by Django 5.1.3 on 2024-11-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_alter_contest_contestants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='code',
            field=models.CharField(max_length=250, verbose_name='Код'),
        ),
        migrations.CreateModel(
            name='ContestDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.contest', verbose_name='Cоревнование')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contests.discipline', verbose_name='Дисциплина')),
            ],
        ),
    ]
