# Generated by Django 5.1.3 on 2024-11-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contest_code_contestdiscipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='age',
        ),
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='contestcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contestcategory',
            name='contest',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contests.contest', verbose_name='Cоревнование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agegroup',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Женщина'), (1, 'Мужчина')], default=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='contest',
            name='female',
            field=models.BooleanField(default=True, verbose_name='Женщины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='male',
            field=models.BooleanField(default=True, verbose_name='Мужчины'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GenderGroup',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ContestCategory',
        ),
    ]
