# Generated by Django 5.1.3 on 2024-11-23 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_rename_disctrict_region_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.district', verbose_name='Федеральный округ'),
        ),
    ]
