# Generated by Django 5.1.3 on 2024-11-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текст уведомления'),
        ),
        migrations.DeleteModel(
            name='NotificationText',
        ),
    ]
